### ISSUE TITLE
Service provider should register package differently

### ISSUE THREAD

**Issue by josephmancuso** [yubarajshrestha/minio-masonite-driver#1]
Service provider register method should look like this:

```python
    def register(self):
        self.application.make('storage').add_driver('minio', MinioDriver(self.application))
```

Doing the way you are doing will remove any drivers set in other service providers because you are creating a new instance of the Storage class (with no drivers) and then registering your own driver to it and then binding the new storage to the container (with your single driver)

**Comment by yubarajshrestha** [comment]
Fixed already in: https://github.com/yubarajshrestha/minio-masonite-driver/commit/77540794780ff908895739366d0e0cb1fe17cdb7
