### ISSUE TITLE
How to get url of stored images in minion?

### ISSUE THREAD

**Issue by Bindukarkee** [yubarajshrestha/minio-masonite-driver#2]
I have problem getting url from minion, once any documents is stored on it.
I tried get method of minio to get the url using following code: 
```python
from masonite.filesystem import Storage

def storeDocument(self, request: Request, storage: Storage):
    file = request.input('file')
    document = storage.disk("minio").put_file('test', file)
    document_url = storage.disk("minio").get(document)
```

But it gives the following error:
```json
{
    "exception": "UnicodeDecodeError",
    "message": "'utf-8' codec can't decode byte 0x89 in position 0: invalid start byte",
    "file": "/home/kodiary/python_project/micro_service/document-service/venv/lib/python3.6/site-packages/minio_driver/MinioDriver.py",
    "trace": [
        {
            "file": "/home/kodiary/python_project/micro_service/document-service/venv/lib/python3.6/site-packages/minio_driver/MinioDriver.py",
            "line": 67,
            "statement": "get"
        },
        {
            "file": "/home/kodiary/python_project/micro_service/document-service/app/controllers/DocumentController.py",
            "line": 39,
            "statement": "storeDocument"
        },
        {
            "file": "/home/kodiary/python_project/micro_service/document-service/venv/lib/python3.6/site-packages/masonite/container/container.py",
            "line": 223,
            "statement": "resolve"
        },
        {
            "file": "/home/kodiary/python_project/micro_service/document-service/venv/lib/python3.6/site-packages/masonite/routes/HTTPRoute.py",
            "line": 193,
            "statement": "get_response"
        },
        {
            "file": "/home/kodiary/python_project/micro_service/document-service/venv/lib/python3.6/site-packages/masonite/providers/RouteProvider.py",
            "line": 49,
            "statement": "boot"
        },
        {
            "file": "/home/kodiary/python_project/micro_service/document-service/venv/lib/python3.6/site-packages/masonite/providers/RouteProvider.py",
            "line": 74,
            "statement": "boot"
        },
        {
            "file": "/home/kodiary/python_project/micro_service/document-service/venv/lib/python3.6/site-packages/masonite/container/container.py",
            "line": 223,
            "statement": "resolve"
        },
        {
            "file": "/home/kodiary/python_project/micro_service/document-service/venv/lib/python3.6/site-packages/masonite/foundation/response_handler.py",
            "line": 27,
            "statement": "response_handler"
        }
    ]
}
```
Could you please help me to get stored document url from minion.

**Comment by yubarajshrestha** [comment]
> I have problem getting url from minion, once any documents is stored on it. I tried get method of minio to get the url using following code:
> 
> ```python
> from masonite.filesystem import Storage
> 
> def storeDocument(self, request: Request, storage: Storage):
>     file = request.input('file')
>     document = storage.disk("minio").put_file('test', file)
>     document_url = storage.disk("minio").get(document)
> ```
> 
> But it gives the following error:
> 
> ```json
> {
>     "exception": "UnicodeDecodeError",
>     "message": "'utf-8' codec can't decode byte 0x89 in position 0: invalid start byte",
>     "file": "/home/kodiary/python_project/micro_service/document-service/venv/lib/python3.6/site-packages/minio_driver/MinioDriver.py",
>     "trace": [
>         {
>             "file": "/home/kodiary/python_project/micro_service/document-service/venv/lib/python3.6/site-packages/minio_driver/MinioDriver.py",
>             "line": 67,
>             "statement": "get"
>         },
>         {
>             "file": "/home/kodiary/python_project/micro_service/document-service/app/controllers/DocumentController.py",
>             "line": 39,
>             "statement": "storeDocument"
>         },
>         {
>             "file": "/home/kodiary/python_project/micro_service/document-service/venv/lib/python3.6/site-packages/masonite/container/container.py",
>             "line": 223,
>             "statement": "resolve"
>         },
>         {
>             "file": "/home/kodiary/python_project/micro_service/document-service/venv/lib/python3.6/site-packages/masonite/routes/HTTPRoute.py",
>             "line": 193,
>             "statement": "get_response"
>         },
>         {
>             "file": "/home/kodiary/python_project/micro_service/document-service/venv/lib/python3.6/site-packages/masonite/providers/RouteProvider.py",
>             "line": 49,
>             "statement": "boot"
>         },
>         {
>             "file": "/home/kodiary/python_project/micro_service/document-service/venv/lib/python3.6/site-packages/masonite/providers/RouteProvider.py",
>             "line": 74,
>             "statement": "boot"
>         },
>         {
>             "file": "/home/kodiary/python_project/micro_service/document-service/venv/lib/python3.6/site-packages/masonite/container/container.py",
>             "line": 223,
>             "statement": "resolve"
>         },
>         {
>             "file": "/home/kodiary/python_project/micro_service/document-service/venv/lib/python3.6/site-packages/masonite/foundation/response_handler.py",
>             "line": 27,
>             "statement": "response_handler"
>         }
>     ]
> }
> ```
> 
> Could you please help me to get stored document url from minion.

Issue has been fixed. You can check the documentation for detail explanation.

```python
file_url = storage.disk("minio").get_secure_url("your_file_key")
```
